-- 사원명이 노옹철인 사원이 속한 부서명을 조회
SELECT DEPT_TITLE
FROM DEPARTMENT
WHERE DEPT_ID = (SELECT DEPT_CODE FROM EMPLOYEE WHERE EMP_NAME = '노옹철');


-- J2 직급의 평균 급여보다 높은 급여를 받는 사원의 이름과 급여를 조회
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE WHERE JOB_CODE = 'J2');


-- 지역코드 L1에 속한 부서에서 근무하는 사원의 이름을 조회
SELECT EMP_NAME
FROM EMPLOYEE
WHERE DEPT_CODE IN (
    SELECT D.DEPT_ID
    FROM DEPARTMENT D
    JOIN LOCATION L ON D.LOCATION_ID = L.LOCAL_CODE
    WHERE L.LOCAL_CODE = 'L1'
);

-- 관리자를 가지고 있는 사원의 이름과 관리자 이름을 조회
SELECT E.EMP_NAME, M.EMP_NAME AS MANAGER_NAME
FROM EMPLOYEE E
JOIN EMPLOYEE M ON E.MANAGER_ID = M.EMP_ID;


-- 부서 코드가 D5인 부서에서 가장 높은 급여를 받는 사원의 이름과 급여를 조회
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEE WHERE DEPT_CODE = 'D5');


-- 퇴사 여부가 N인 사원 중 가장 적은 급여를 받는 사원의 이름과 급여를 조회
SELECT EMP_NAME, SALARY
FROM EMPLOYEE
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEE WHERE Ent_yn  = 'N');


-- 부서 코드가 D8인 부서에서 입사일이 가장 빠른 사원의 이름과 입사일을 조회
SELECT EMP_NAME, HIRE_DATE
FROM EMPLOYEE
WHERE HIRE_DATE = (SELECT MIN(HIRE_DATE) FROM EMPLOYEE WHERE DEPT_CODE = 'D8');

-- 전 사원의 최대 급여와 최소 급여를 조회
SELECT 
    (SELECT MAX(SALARY) FROM EMPLOYEE) AS MAX_SALARY,
    (SELECT MIN(SALARY) FROM EMPLOYEE) AS MIN_SALARY;å
